version: "3"
services:
  app:
    build: .
    volumes:
      - ".:/app"
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/app"
    command: "go test ./..."
